<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\OrdersController;

// Home Route (you can customize or add a home controller later)
Route::get('/home', function () {
    return redirect()->route('products.index');
});

// Product Routes
/*/products: Displays the list of all products.
/products/{id}: Displays the details of an individual product. */
Route::get('/products', [ProductController::class, 'index'])->name('products.index'); // List all products
Route::get('/products/{id}', [ProductController::class, 'show'])->name('products.show'); // Show individual product details

// Cart Routes
/*/cart: Displays the current items in the shopping cart.
/cart/add/{id}: Adds a product to the cart by its ID.
/cart/remove/{id}: Removes a product from the cart by its ID. */
Route::get('/cart', [CartController::class, 'index'])->name('cart.index'); // View cart
Route::post('/cart/add/{id}', [CartController::class, 'add'])->name('cart.add'); // Add product to cart
Route::delete('/cart/remove/{id}', [CartController::class, 'remove'])->name('cart.remove'); // Remove product from cart

// Checkout Routes
/* /checkout: Displays the checkout page, where users can enter payment information.
/checkout (POST): Processes the payment through Stripe and stores the order in the database.*/
Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout.index'); // Show checkout page
Route::post('/checkout', [CheckoutController::class, 'processPayment'])->name('checkout.process'); // Process payment

// Order Routes
/*/orders: Displays the list of orders for the authenticated user. */
Route::get('/orders', [OrdersController::class, 'index'])->name('orders.index'); // View user's orders

// Authentication Routes (generated by Laravel Breeze or UI or user registration, login, etc)
Auth::routes();
